<a href="https://colab.research.google.com/github/IT-HONGREAT/studying/blob/main/%3Fstack%2C%3Fsplit%2Cview%2Ccopy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

arr1 = np.array([[1,1],[2,2]])
arr2 = np.array([[3,3],[4,4]])

arr_vstack = np.vstack((arr1,arr2))

print(arr_vstack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [6]:
import numpy as np

arr1 = np.array([[1,1],[2,2]])
arr2 = np.array([[3,3],[4,4]])

arr_hstack = np.hstack((arr1,arr2))

print(arr_hstack)


[[1 1 3 3]
 [2 2 4 4]]


In [10]:
arr = np.arange(1,25).reshape(6,4)
print(arr)
print()
arr1, arr2, arr3 = np.vsplit(arr,3)
print(arr1)

print(arr2)

print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]]


In [24]:
import numpy as np
arr = np.arange(1,25).reshape(2,12)
print(arr)


arr_col1,arr_col2,arr_col3 = np.hsplit(arr,3)

print(arr_col1)

print(arr_col2)

print(arr_col3)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[[ 1  2  3  4]
 [13 14 15 16]]
[[ 5  6  7  8]
 [17 18 19 20]]
[[ 9 10 11 12]
 [21 22 23 24]]


In [28]:
arr1 = np.array([[0,1,2,3],
                 [4,5,6,7],
                 [8,9,10,11]])

arr2 = arr1
print(arr2 is arr1)

True


In [45]:
arr1 = np.array([[0,1,2,3],
                 [4,5,6,7],
                 [8,9,10,11]])

arr2 = arr1.view()  
#arr.view()  연결되는 다른 복사본을 만든것. 얕은 복사방식!사실 복사본의 개념이라기 보다 해당함수가 어떤 것인지 봐주는 것이라고 생각하자.

print(arr1 is arr2)
print(arr2)

False
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
arr1[0] = 999
print(arr2)

[[999 999 999 999]
 [  4   5   6   7]
 [  8   9  10  11]]


In [42]:
print(id(arr1))

140436744571840


In [46]:
print(id(arr2))

140436741913616


In [49]:
arr1 = np.array([[0,1,2,3],
                 [4,5,6,7],
                 [8,9,10,11]])

arr2 = arr1.copy()  #깊은 복사 방식으로, 다른 변수에 지정해주는 것이다.
print(arr1 is arr2)

False


In [52]:
arr1[0] = 999
print(arr1)

[[999 999 999 999]
 [  4   5   6   7]
 [  8   9  10  11]]


In [53]:
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [54]:
print(id(arr1))

140436742695152


In [55]:
print(id(arr2))

140436744653280
