<a href="https://colab.research.google.com/github/IT-HONGREAT/studying/blob/main/array_%EC%A1%B0%EA%B1%B4%EC%9E%91%EC%84%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr[arr<5])  #arr[arr조건] 을 쓰면 해당 조건에 부합하는 것만 출력된다.

[1 2 3 4]


In [5]:
arr5 = (arr >= 5)   #조건 자체를 변수 지정
print(arr[arr5])

[ 5  6  7  8  9 10 11 12]


In [7]:
arr2 = arr[(arr>2) & (arr< 11)]    #& 혹은 | 도 사용가능!
print(arr2)

[ 3  4  5  6  7  8  9 10]


In [13]:
arr = np.array([[[5 ,2 ,4 ,6 ,7],
        [3, 8, 9, 1, 0]],
 
        [[6, 5, 7, 1, 3],
        [8, 9 ,4, 0 ,2]],
 
        [[5 ,8, 6, 9, 2],
        [1 ,3 ,4, 0 ,7]]])

arr[arr < 5] = 0
print(arr)

[[[5 0 0 6 7]
  [0 8 9 0 0]]

 [[6 5 7 0 0]
  [8 9 0 0 0]]

 [[5 8 6 9 0]
  [0 0 0 0 7]]]
