<a href="https://colab.research.google.com/github/IT-HONGREAT/studying/blob/main/array_%EC%9D%B8%EB%8D%B1%EC%8B%B1_%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

arr = np.arange(10).reshape(2,5)

print(arr)
print(arr[0,3])    #[0][3] 과 같지만 []자체가 접근이라는 하나의 동작이기때문에 비효율적.
print(arr[1,-1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
3
9


In [9]:
arr = np.arange(20).reshape(5,4)

print(arr)
print(arr[2,3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
11


In [19]:
arr = np.arange(20).reshape(5,4)

print(arr)
print(arr[0:4,1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ 1  5  9 13]


In [18]:
arr = np.arange(20).reshape(5,4)

print(arr)
print(arr[0:4,1].reshape(4,1))  #출력을 세로로 하고 싶어서 reshape 을 써봤다.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 1]
 [ 5]
 [ 9]
 [13]]


In [21]:
arr = np.arange(20).reshape(5,4)

print(arr)
print(arr[0:2,:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[0 1 2 3]
 [4 5 6 7]]


In [37]:
arr = np.arange(42).reshape(6,7)

print(arr)
print(arr[2,3])
print(arr[5,0])
print(arr[3,6])
print(arr[0,1])

print(arr[5,3])
print(arr[4,1])
print(arr[1,6])
print(arr[-1,-1])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
17
35
27
1
38
29
13
41


In [48]:
arr = np.arange(42).reshape(6,7)

print(arr)
print(arr[:,3])
print(arr[4,:])
print(arr[1,:])
print(arr[:,-1])
print()
print(arr[:,1])
print(arr[0,:])
print(arr[5,:])
print(arr[:,5])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
[ 3 10 17 24 31 38]
[28 29 30 31 32 33 34]
[ 7  8  9 10 11 12 13]
[ 6 13 20 27 34 41]

[ 1  8 15 22 29 36]
[0 1 2 3 4 5 6]
[35 36 37 38 39 40 41]
[ 5 12 19 26 33 40]


In [58]:
arr = np.arange(42).reshape(6,7)

print(arr)
print(arr[:,1:4])
print(arr[2:5,:])
print(arr[1:3,:])
print(arr[:,-2:])
print()
print(arr[:,3:6])
print(arr[1:,:])
print(arr[:2,:])
print(arr[:,1:6])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
[[ 1  2  3]
 [ 8  9 10]
 [15 16 17]
 [22 23 24]
 [29 30 31]
 [36 37 38]]
[[14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[[ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[ 5  6]
 [12 13]
 [19 20]
 [26 27]
 [33 34]
 [40 41]]

[[ 3  4  5]
 [10 11 12]
 [17 18 19]
 [24 25 26]
 [31 32 33]
 [38 39 40]]
[[ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
[[ 1  2  3  4  5]
 [ 8  9 10 11 12]
 [15 16 17 18 19]
 [22 23 24 25 26]
 [29 30 31 32 33]
 [36 37 38 39 40]]


In [63]:
arr = np.arange(42).reshape(6,7)

print(arr)
print(arr[-2:,3:5])
print(arr[1:,5:7])
print(arr[1:4,2:5])
print(arr[1:4,:3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
[[31 32]
 [38 39]]
[[12 13]
 [19 20]
 [26 27]
 [33 34]
 [40 41]]
[[ 9 10 11]
 [16 17 18]
 [23 24 25]]
[[ 7  8  9]
 [14 15 16]
 [21 22 23]]


In [74]:
arr = np.arange(50).reshape(2,5,5)  #3차원 배열을 만드는 reshape 꼭 기억해둘것.

print(arr)
print(arr[0,2,:])
print(arr[1,:,-1])
print()
print(arr[1,:3,:])
print(arr[0,:,2:4])
print()
print(arr[0,1:4,1:3])
print(arr[1,1:-1,:4])
print()
print(arr[:,:2,2:4])
print(arr[:,2:,1:4])


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]
[10 11 12 13 14]
[29 34 39 44 49]

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]
 [22 23]]

[[ 6  7]
 [11 12]
 [16 17]]
[[30 31 32 33]
 [35 36 37 38]
 [40 41 42 43]]

[[[ 2  3]
  [ 7  8]]

 [[27 28]
  [32 33]]]
[[[11 12 13]
  [16 17 18]
  [21 22 23]]

 [[36 37 38]
  [41 42 43]
  [46 47 48]]]
