<a href="https://colab.research.google.com/github/IT-HONGREAT/studying/blob/main/concatenate_delete_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np

arr1 = np.array([[[19,17,10,8,3],
                 [5,12,9,0,1]]
                 ,
                 [[11,6,16,15,14],
                 [4,2,13,18,7]
                 ]])
arr2 = np.array([[[13,1,7,3],
                 [15,5,2,14]]
                 ,
                 [[4,12,11,10],
                 [8,6,9,0]]])

a = np.concatenate((arr1,arr2),axis = 2)

print(a)


[[[19 17 10  8  3 13  1  7  3]
  [ 5 12  9  0  1 15  5  2 14]]

 [[11  6 16 15 14  4 12 11 10]
  [ 4  2 13 18  7  8  6  9  0]]]


In [32]:
import numpy as np

arr1 = np.zeros((3,5,4))
arr2 = np.zeros((3,5,1))

a = np.concatenate((arr1,arr2),axis = 2)

print(a)


[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [35]:
import numpy as np
from PIL import Image

img = np.asarray(Image.open('lena.png'))

img = img.copy()
img2 = img.copy()

img = np.concatenate((img,img2),1)

img = Image.fromarray(img, 'RGB')
img.save('out.png')



In [59]:
arr = np.array([[[1,4,20,23,28],
                [13,8,24,21,5]]
                ,
               [[25,29,26,18,2],
                [14,27,9,10,3]],

               [[21,29,26,18,2],
                [13,27,9,10,3]]])


arr = np.delete(arr,(0,1),2)


print(arr)

[[[20 23 28]
  [24 21  5]]

 [[26 18  2]
  [ 9 10  3]]

 [[26 18  2]
  [ 9 10  3]]]


In [62]:
array_example = np.array([[[0,1,2,3,4],
                          [5,6,7,8,9]],
                          
                          [[10,11,12,13,14],
                          [10,11,12,13,14]]])

array_example.ndim #차원 수를 표현

3

In [63]:
array_example = np.array([[[0,1,2,3,4],
                          [5,6,7,8,9]],
                          
                          [[10,11,12,13,14],
                          [10,11,12,13,14]]])

array_example.size   #총 원소수 배열 shape 곱하면 됨.

20

In [64]:
array_example = np.array([[[0,1,2,3,4],
                          [5,6,7,8,9]],
                          
                          [[10,11,12,13,14],
                          [10,11,12,13,14]]])

array_example.shape #배열 모양알려줌

(2, 2, 5)

In [69]:
arr1 = np.arange(18)

print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [71]:
arr2 = arr1.reshape(6,3)

print(arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [73]:
arr = np.array([[1,2,3],[4,5,6]])

arr = np.reshape(arr,(3,-1))  #-1이 거꾸로가 아니라, 원래 배열길이와 남은 차원에서 유추한 자동변경을 의미.

print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [83]:
arr = np.arange(4)

arr = np.reshape(arr,(2,2))

print(arr)

[[0 1]
 [2 3]]


In [86]:
arr = np.arange(16)

arr = np.reshape(arr,(4,4))

print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [89]:
arr = np.arange(35)

arr = np.reshape(arr,(5,7))

print(arr)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [96]:
#3차원  ;  어려울 것 없이 약수들 의 곱 정도로 생각하자.

arr = np.arange(72)

arr = np.reshape(arr,(3,2,12))

print(arr)

[[[ 0  1  2  3  4  5  6  7  8  9 10 11]
  [12 13 14 15 16 17 18 19 20 21 22 23]]

 [[24 25 26 27 28 29 30 31 32 33 34 35]
  [36 37 38 39 40 41 42 43 44 45 46 47]]

 [[48 49 50 51 52 53 54 55 56 57 58 59]
  [60 61 62 63 64 65 66 67 68 69 70 71]]]


In [101]:
import numpy as np
from PIL import Image

img = np.asarray(Image.open('lena.png'))

# img = img.copy()
# img2 = img.copy()

img = img.reshape(256,1024,3)

img = Image.fromarray(img, 'RGB')
img.save('out.png')

