<a href="https://colab.research.google.com/github/IT-HONGREAT/studying/blob/main/newaxis%26expand_dims().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

print(arr.shape)
print(arr)
print()
arr2 = arr[np.newaxis,:]
print(arr.shape)
print(arr2)
print()

col_vector = arr[:,np.newaxis]
print(col_vector.shape)
print(col_vector)

(6,)
[1 2 3 4 5 6]

(6,)
[[1 2 3 4 5 6]]

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [11]:
arr = np.arange(20).reshape(4,5)
print(arr)
print()
arr = arr[:,np.newaxis]  # 2번째 차원에 새로운 축(차원) 추가
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]

 [[15 16 17 18 19]]]


In [14]:
arr = np.arange(10,40).reshape(6,5)
print(arr)
print()
arr = arr[np.newaxis,:]   # 1번째 차원에 새로운 축(차원) 추가
print(arr)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]

[[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [18]:
arr = np.array([[[1],[2],[3]],[[4],[5],[6]]])
print((arr.shape))

print()

arr4 = arr[:, np.newaxis,:,:]
print(arr4.shape)

(2, 3, 1)

(2, 1, 3, 1)


In [11]:
import numpy as np
arr = np.array([1,2,3])
print(arr.shape)
print()
arr2 = np.expand_dims(arr,axis = 0)
print(arr2)
print(arr2.shape)
print()
arr3 = np.expand_dims(arr,axis = -1)
# arr3 = np.expand_dims(arr3,axis = -1)
print(arr3)
print(arr3.shape)

(3,)

[[1 2 3]]
(1, 3)

[[1]
 [2]
 [3]]
(3, 1)


In [4]:
import numpy as np
arr = np.arange(3)

print(arr)

[0 1 2]


In [7]:
arr1 = arr[:,np.newaxis]
print(arr1)

[[0]
 [1]
 [2]]


In [9]:
arr2 = arr[:,np.newaxis]*arr
print(arr2)

[[0 0 0]
 [0 1 2]
 [0 2 4]]


In [10]:
arr3 = arr[:,np.newaxis]+arr
print(arr3)

[[0 1 2]
 [1 2 3]
 [2 3 4]]
