<a href="https://colab.research.google.com/github/IT-HONGREAT/studying/blob/main/randint%2Cunique.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

print(np.random.randint(2,size = 10))

print(np.random.randint(45,size=(5,5,5)))
# num = np.random.randint(45,size=(5,5,5))


[1 0 1 1 0 1 1 1 0 0]
[[[16 18 31  4 40]
  [11 12  3 39 14]
  [33 32 15 26 22]
  [27  7 40 39 37]
  [28  6 33 12 26]]

 [[ 2  8 19 44  1]
  [20 12 10  1 44]
  [ 6  9  1  1 40]
  [11 12  8 20 34]
  [24 23 11  8 28]]

 [[12 33 20 34 31]
  [21 10  0 34 19]
  [30 13 24 32 25]
  [39 39 44 17 18]
  [41 27 23 22 34]]

 [[41  6 29 14 32]
  [34 40  3 21 15]
  [20 39 37 43 30]
  [11 40 28 12 36]
  [27  6 29 41 39]]

 [[12 15  5 37 42]
  [16  8 29 25 12]
  [40 33 38 40 19]
  [20 23  7  9 14]
  [29 41  6 39 15]]]


In [14]:
print(np.random.rand(3,2))

[[0.28118944 0.97771374]
 [0.12330473 0.57694519]
 [0.04199513 0.97185453]]


In [16]:
print(np.random.randn(2,4))

[[ 0.38227093 -0.6605199   0.13790328  1.28365562]
 [-1.2077721  -2.19351542  0.97413872 -0.56122842]]


In [21]:
arr = np.arange(10)
print(arr)
np.random.shuffle(arr)
print(arr)
#셔플은 첫번째 축을 기준으로만 섞는다

arr = np.arange(9).reshape((3,3))
print(arr)
np.random.shuffle(arr)
print(arr)
#전체가 뒤죽박죽으로 섞인 걸 원한다면, 처음에 셔플을 돌리고 reshape을 하자.

[0 1 2 3 4 5 6 7 8 9]
[3 5 7 2 8 9 1 6 0 4]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [33]:
print(np.random.choice(5,3,p = [0.1,0,0.3,0.6,0]))

zoo = ['lion','elephant','monkey']
print(np.random.choice(zoo,5,p=[0.5,0.1,0.4]))

[2 3 2]
['lion' 'monkey' 'lion' 'monkey' 'monkey']


In [45]:
arr = np.array([11,11,12,13,14,15,16,17,12,13,11,14,18,19,20])
unique_values = np.unique(arr)
print(unique_values)

unique_values = np.unique(arr,return_index=True)  #중복된 값을 제거한 배열에서 각 값이 원래배열에서 처음 나타난 위치 
print(unique_values)


unique_values = np.unique(arr,return_inverse=True)  #각 값의 위치
print(unique_values)


unique_values = np.unique(arr,return_counts=True) #각 값이 나타나는 횟수
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]
(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))
(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), array([0, 0, 1, 2, 3, 4, 5, 6, 1, 2, 0, 3, 7, 8, 9]))
(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))


In [48]:
arr = np.arange(4).reshape((2,2))
print(arr)

[[0 1]
 [2 3]]


In [50]:
print(np.transpose(arr))  #행렬의 전치

[[0 2]
 [1 3]]


In [53]:
arr = np.ones((1,2,3))
print(arr)
print(np.transpose(arr,(1,0,2)).shape)

[[[1. 1. 1.]
  [1. 1. 1.]]]
(2, 1, 3)


In [57]:
#transpose() 와 동일한 ndarray.T

arr = np.array([[1.,2.],[3.,4.]])
print(arr)

print(arr.T)

[[1. 2.]
 [3. 4.]]
[[1. 3.]
 [2. 4.]]


In [59]:
arr = np.array([1.,2.,3.,4.])
print(arr)

[1. 2. 3. 4.]


In [61]:
arr = np.array([[1.,2.,3.,4.]])
print(arr.T)

[[1.]
 [2.]
 [3.]
 [4.]]
