<a href="https://colab.research.google.com/github/IT-HONGREAT/colab_study/blob/main/%EB%94%A5%EB%9F%AC%EB%8B%9D%EA%B0%95%EC%9D%98_210630.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
real = [21,10,14]
pre = [15,12,18]

answer = 0

for i in range(len(real)):
  answer += ((real[i]-pre[i])**2)

print(answer/len(real))

18.666666666666668


In [3]:
y_1 = 21
y_2 = 10
y_3 = 14

y_hat_1 = 15
y_hat_2 = 12
y_hat_3 = 18

a = (y_1 - y_hat_1)**2
b = (y_2 - y_hat_2)**2
c = (y_3 - y_hat_3)**2

print(a,b,c)

36 4 16


In [6]:
import numpy as np
n = 3
mse = (a+b+c)/n

print(f"mse : {np.round(mse,4)}")

mse : 18.6667


In [16]:
#case1

one_rows = ['M',0.455,0.365,0.095]   #m의 경우 [1,0,0]
one_row = [0.455,0.365,0.095]
proto = [0,0,0]+one_row

if 'M' in one_rows:
  proto[0] = 1

print(proto)



[1, 0, 0, 0.455, 0.365, 0.095]


In [17]:
def sep(rows):

  if "M" in rows:
    rows[0] = 1
  elif 'F' in rows:
    rows[1] = 1
  elif 'I' in rows:
    rows[2] = 1
  
  return rows



In [19]:
rows = ['M',0.455,0.365,0.095]

data = np.zeros(6)

print(data)
 

[0. 0. 0. 0. 0. 0.]


In [21]:
if rows[0] =='M':
  data[0] = 1
elif rows[0] == 'F':
  data[1] = 1
elif rows[1] == 'I':
  data[2] = 1

print(data)

[1. 0. 0. 0. 0. 0.]


In [23]:
print(rows)

print("======")

print(data)

['M', 0.455, 0.365, 0.095]
[1. 0. 0. 0. 0. 0.]


In [25]:
data[3:] = rows[1:]
print(data)

[1.    0.    0.    0.455 0.365 0.095]


In [26]:
import csv

In [47]:
with open('/content/abalone_mini.csv') as csvfile:
  csvreader = csv.reader(csvfile) 

  rows = []

  for row in csvreader:
    rows.append(row)

In [48]:
print(rows)

[['M', '0.455', '0.365', '0.095', '0.514', '0.2245', '0.101', '0.15', '15'], ['M', '0.35', '0.265', '0.09', '0.2255', '0.0995', '0.0485', '0.07', '7'], ['F', '0.53', '0.42', '0.135', '0.677', '0.2565', '0.1415', '0.21', '9'], ['M', '0.44', '0.365', '0.125', '0.516', '0.2155', '0.114', '0.155', '10'], ['I', '0.33', '0.255', '0.08', '0.205', '0.0895', '0.0395', '0.055', '7']]


In [49]:
data = np.zeros([5,11])
print(data)
  


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [55]:
for idx,row in enumerate(rows):
  
  if row[0] == 'M' : data[idx,0] = 1
  if row[0] == 'F' : data[idx,1] = 1
  if row[0] == 'I' : data[idx,2] = 1


  data[idx,3:] = row[1:]

data

array([[ 1.    ,  0.    ,  0.    ,  0.455 ,  0.365 ,  0.095 ,  0.514 ,
         0.2245,  0.101 ,  0.15  , 15.    ],
       [ 1.    ,  0.    ,  0.    ,  0.35  ,  0.265 ,  0.09  ,  0.2255,
         0.0995,  0.0485,  0.07  ,  7.    ],
       [ 0.    ,  1.    ,  0.    ,  0.53  ,  0.42  ,  0.135 ,  0.677 ,
         0.2565,  0.1415,  0.21  ,  9.    ],
       [ 1.    ,  0.    ,  0.    ,  0.44  ,  0.365 ,  0.125 ,  0.516 ,
         0.2155,  0.114 ,  0.155 , 10.    ],
       [ 0.    ,  0.    ,  1.    ,  0.33  ,  0.255 ,  0.08  ,  0.205 ,
         0.0895,  0.0395,  0.055 ,  7.    ]])

In [57]:
import pandas as pd

ans = pd.DataFrame(data)
ans

0    1    2      3      4      5       6       7       8      9     10
0  1.0  0.0  0.0  0.455  0.365  0.095  0.5140  0.2245  0.1010  0.150  15.0
1  1.0  0.0  0.0  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.070   7.0
2  0.0  1.0  0.0  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.210   9.0
3  1.0  0.0  0.0  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.155  10.0
4  0.0  0.0  1.0  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.055   7.0