<a href="https://colab.research.google.com/github/IT-HONGREAT/studying/blob/main/%EB%B0%B0%EC%97%B4%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
arr1 = np.array([1,2])
arr2 = np.ones(2, dtype = int)

print(arr1+arr2)

print(arr1-arr2)

print(arr1*arr2)  #간단하게 각 원소 끼리 의 사칙 연산이고, 행렬곱이 아니다.

print(arr1/arr2)


[2 3]
[0 1]
[1 2]
[1. 2.]


In [9]:
arr = np.array([1,2,3,4])

print(arr.sum())

10


In [11]:
arr = np.array([[1,1],[2,2]])

print(arr.sum(axis = 0)) #0축 기준 으로 

print(arr.sum(axis = 1)) #1축 기준으로 

[3 3]
[2 4]


In [14]:
arr = np.array([[4,2,5,7,2,7],
               [9,54,3,8,4,67],
               [14,36,58,547,32,7]])

print(arr.max(axis=0))
print(arr.max(axis=1))
print(arr.max())

[ 14  54  58 547  32  67]
[  7  67 547]
547


In [18]:
arr = np.array([[4,2,5,7,2,7],
               [9,54,3,8,4,67],
               [14,36,58,547,32,7]])

print(arr.mean(axis = 0))
print(arr.mean(axis = 1))
print(arr.mean())

[  9.          30.66666667  22.         187.33333333  12.66666667
  27.        ]
[  4.5         24.16666667 115.66666667]
48.111111111111114


In [20]:
arr = np.array([[4,2,5,7,2,7],
               [9,54,3,8,4,67],
               [14,36,58,547,32,7]])

print(arr.std(axis = 0))
print(arr.std(axis = 1))
print(arr.std())

[  4.0824829   21.56128217  25.46893533 254.32306663  13.69509239
  28.28427125]
[  2.06155281  26.04749935 193.59120733]
122.74539542795661


In [21]:
arr = np.array([[4,2,5,7,2,7],
               [9,54,3,8,4,67],
               [14,36,58,547,32,7]])

print(arr.prod(axis = 0))
print(arr.prod(axis = 1))
print(arr.prod())

[  504  3888   870 30632   256  3283]
[      3920    3125952 3581738496]
6996174903569809408


In [27]:
arr1 = np.eye(2) # 단위행렬 만들어주는 함수 eye()
arr2 = np.ones((2,2)) * 2

print(arr1)
print(arr2)
print("")
print(arr1.dot(arr2))

[[1. 0.]
 [0. 1.]]
[[2. 2.]
 [2. 2.]]

[[2. 2.]
 [2. 2.]]


In [28]:
print(arr1.dot(arr2).dot(arr2))  #연결해서 사용가능!!

[[8. 8.]
 [8. 8.]]


In [29]:
arr1 = np.array([[1,0],[0,1]])
arr2 = np.array([[4,1],[2,2]])

print(np.matmul(arr1,arr2))

[[4 1]
 [2 2]]
